export const data = {
  template: {
    name: "template2",
    color: "#16a34a",
    sections: {
      left: ["experiences", "education"],
      right: [
        "skills",
        "projects",
        "certifications",
        "languages",
        "references",
        "hobbies",
      ],
    },
  },
  personalData: {
    name: "John Doe",
    title: "Développeur Web Frontend",
    email: "john@doe.com",
    tel: "+41 79 123 45 67",
    nationality: "Français",
    permit: "Permis C",
    age: "32",
    city: "Lausanne",
    country: "Suisse",
    linkedinUrl: "linkedin.com/in/johndoe/",
  },
  experiences: [
    {
      company: "Rolex",
      companyDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      title: "CTO",
      city: "",
      country: "Suisse",
      current: true,
      fromMonth: "08",
      fromYear: "2021",
      toMonth: "",
      toYear: "",
      description:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Excepteur sint occaecat cupidatat non proident.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":2}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    },
    {
      company: "Migros",
      companyDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      title: "Développeur web fullstack",
      city: "",
      country: "Suisse",
      current: false,
      fromMonth: "03",
      fromYear: "2015",
      toMonth: "07",
      toYear: "2021",
      description:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Excepteur sint occaecat cupidatat non proident.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":2}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    },
    {
      company: "Nestlé",
      companyDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      title: "Développeur web junior",
      city: "",
      country: "Suisse",
      current: false,
      fromMonth: "04",
      fromYear: "2012",
      toMonth: "02",
      toYear: "2015",
      description:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Excepteur sint occaecat cupidatat non proident.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":2}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    },
  ],
  skills: [
    { skill: "HTML" },
    { skill: "CSS" },
    { skill: "Tailwindcss" },
    { skill: "Javascript" },
    { skill: "React.js" },
    { skill: "Vue.js" },
    { skill: "Next.js" },
    { skill: "Ruby" },
    { skill: "Ruby On Rails" },
    { skill: "Git" },
  ],
  education: [
    {
      school: "Insa",
      degree: "Master",
      field: "Sécurité Informatique",
      country: "France",
      city: "Lyon",
      fromMonth: "09",
      fromYear: "2010",
      toMonth: "06",
      toYear: "2012",
      description:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    },
    {
      school: "Epitech",
      degree: "License (Bachelor)",
      field: "Informatique",
      country: "France",
      city: "Paris",
      fromMonth: "09",
      fromYear: "2007",
      toMonth: "06",
      toYear: "2010",
      description:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    },
  ],
  references: [
    {
      name: "Roger The Goat",
      company: "Rolex",
      position: "CEO",
      email: "",
      tel: "",
    },
    {
      name: "Stan Imal",
      company: "Migros",
      position: "CTO",
      email: "",
      tel: "",
    },
  ],
  certifications: [
    {
      title: "Javascript, The Complete Guide",
      issuer: "Udemy",
      month: "03",
      year: "2020",
    },
    {
      title: "React, The Complete Guide",
      issuer: "Udemy",
      month: "10",
      year: "2019",
    },
    {
      title: "Vue.js, The Complete Guide",
      issuer: "Udemy",
      month: "12",
      year: "2018",
    },
  ],
  languages: [
    {
      language: "Français",
      level: "Courant, Langue maternelle",
    },
    {
      language: "Anglais",
      level: "Niveau C1",
    },
  ],
  projects: [
    {
      title: "Générateur de CV",
      description:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
      link: "https://github.com/JohDoe/cv-builder",
      current: "true",
      fromMonth: "10",
      fromYear: "2023",
      toMonth: "",
      toYear: "",
    },
  ],
  summary:
    '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
};
