export const data = {
  template: "template2",
  personalData: {
    name: "John Doe",
    title: "Développeur Web Frontend",
    email: "john@doe.com",
    tel: "+41 79 123 45 67",
    nationality: "Français",
    permit: "Permis C",
    age: "32",
    city: "Lausanne",
    country: "Suisse",
    linkedinUrl: "linkedin.com/in/johndoe/",
  },
  experiences: [
    {
      company: "Google",
      companyDesc: "PME Américaine qui développe des logiciels.",
      title: "Développeur web senior",
      city: "",
      country: "USA",
      current: true,
      fromMonth: "08",
      fromYear: "2021",
      toMonth: "",
      toYear: "",
      description: [
        { task: "Développement d'un moteur de recherche." },
        {
          task: "Développement d'un client mail utilisé par 1 milliard de personnes.",
        },
        {
          task: "Développement d'un navigateur web utilisé par plus de 3 milliards de personnes.",
        },
      ],
    },
    {
      company: "Apple",
      companyDesc: "Société qui fabrique et vend des appareils technologiques.",
      title: "Développeur Web Fullstack",
      city: "",
      country: "USA",
      current: false,
      fromMonth: "03",
      fromYear: "2015",
      toMonth: "07",
      toYear: "2021",
      description: [
        { task: "Développement du site web de l'entreprise." },
        {
          task: "Développement du frontend du back office de l'entreprise.",
        },
        {
          task: "Développement de l'Apple Store.",
        },
      ],
    },
    {
      company: "Facebook",
      companyDesc: "Réseau social.",
      title: "Développeur Web Junior",
      city: "",
      country: "USA",
      current: false,
      fromMonth: "04",
      fromYear: "2012",
      toMonth: "02",
      toYear: "2015",
      description: [
        { task: "Développement du réseau social du même nom." },
        {
          task: "Développement d'une application de petites annonces entre particuliers.",
        },
        {
          task: "Développement de nouvelles fonctionnalités de l'application de messagerie de l'entreprise.",
        },
      ],
    },
  ],
  skills: [
    { skill: "HTML" },
    { skill: "CSS" },
    { skill: "Tailwindcss" },
    { skill: "Javascript" },
    { skill: "React.js" },
    { skill: "Vue.js" },
    { skill: "Next.js" },
    { skill: "Ruby" },
    { skill: "Ruby On Rails" },
    { skill: "Git" },
  ],
  education: [
    {
      school: "Université Claude Bernard Lyon 1",
      degree: "Master",
      field: "Ingénierie des Risques / Spécialité Sécurité Informatique",
      country: "France",
      city: "Lyon",
      fromMonth: "09",
      fromYear: "2010",
      toMonth: "06",
      toYear: "2012",
      description: "",
    },
    {
      school: "Université Claude Bernard Lyon 1",
      degree: "License (Bachelor)",
      field: "Mathématiques / Informatique",
      country: "France",
      city: "Lyon",
      fromMonth: "09",
      fromYear: "2007",
      toMonth: "06",
      toYear: "2010",
      description: "",
    },
  ],
  references: [
    {
      name: "Larry Page",
      company: "Google",
      position: "Informaticien",
      email: "",
      tel: "",
    },
    {
      name: "Tim Cook",
      company: "Apple",
      position: "CEO",
      email: "",
      tel: "",
    },
    {
      name: "Mark Zuckerberg",
      company: "Facebook",
      position: "CEO",
      email: "",
      tel: "",
    },
  ],
  certifications: [
    {
      title: "Javascript, The Complete Guide",
      issuer: "Udemy",
      month: "03",
      year: "2020",
    },
    {
      title: "React, The Complete Guide",
      issuer: "Udemy",
      month: "10",
      year: "2019",
    },
    {
      title: "Vue.js, The Complete Guide",
      issuer: "Udemy",
      month: "12",
      year: "2018",
    },
  ],
  languages: [
    {
      language: "Français",
      level: "Courant, Langue maternelle",
    },
    {
      language: "Anglais",
      level: "Niveau C1",
    },
  ],
  projects: [
    {
      title: "Générateur de CV",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      link: "https://github.com/JohDoe/cv-builder",
      current: "true",
      fromMonth: "10",
      fromYear: "2023",
      toMonth: "",
      toYear: "",
    },
  ],
  summary:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
};
